# Generated by Django 3.1 on 2020-08-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('caste', models.CharField(default='GEN', max_length=10)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_from_school', models.IntegerField(default=0)),
                ('electricity', models.IntegerField(default=0)),
                ('environment', models.CharField(default='YES', max_length=3)),
                ('uid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data.aadhar')),
            ],
        ),
    ]
