# Generated by Django 3.1 on 2020-08-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_accessibility_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibility',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.aadhar'),
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicles', models.IntegerField()),
                ('public_vehicles', models.IntegerField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
                ('members', models.IntegerField()),
                ('any_student_aid', models.CharField(default='NO', max_length=3)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop', models.CharField(default='NO', max_length=3)),
                ('smartphone', models.CharField(default='NO', max_length=3)),
                ('internet', models.CharField(default='NO', max_length=3)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.aadhar')),
            ],
        ),
    ]
