# Generated by Django 3.1 on 2020-08-21 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200821_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhar',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='disability',
            field=models.CharField(default='YES', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='education_qualification',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='health_aids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(default='unmarried', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_insurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='taluk',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='village',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='aadhar',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MedicalAccessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearest_hospital', models.IntegerField(default=0)),
                ('four_wheeler', models.CharField(default='NO', max_length=3)),
                ('nearest_pharmacy', models.IntegerField(default=0)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agriculture_area', models.IntegerField(default=0)),
                ('ancestral_land', models.IntegerField(default=0)),
                ('total_value_of_possession', models.IntegerField(default=0)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentlyResiding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented', models.CharField(default='NO', max_length=3)),
                ('area', models.IntegerField(default=0)),
                ('water_quantity', models.IntegerField(default=0)),
                ('water_quality', models.IntegerField(default=0)),
                ('electricity_facility', models.CharField(default='', max_length=30)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_disease', models.CharField(max_length=30)),
                ('heredity_disease', models.CharField(max_length=30)),
                ('bedridden', models.CharField(default='NO', max_length=3)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_scheme', models.IntegerField(default=0)),
                ('medicinal_scheme', models.IntegerField(default=0)),
                ('housing_scheme', models.IntegerField(default=0)),
                ('land_scheme', models.IntegerField(default=0)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.aadhar')),
            ],
        ),
    ]
