# Generated by Django 3.1 on 2020-08-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200822_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='financial_scheme',
            field=models.IntegerField(default=0),
        ),
    ]
