# Generated by Django 3.1 on 2020-08-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_credits_financial_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthealth',
            name='heredity_disease',
            field=models.CharField(default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='currenthealth',
            name='terminal_disease',
            field=models.CharField(default='NO', max_length=3),
        ),
    ]
