# Generated by Django 3.1 on 2020-08-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200822_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthealth',
            name='heredity_disease',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='currenthealth',
            name='terminal_disease',
            field=models.CharField(max_length=30),
        ),
    ]
